<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title }} | PakFlex Packaging</title><meta name="description" content="{{ $description }}"><link rel="canonical" href="{{ url()->current() }}"><meta name="theme-color" content="#102a43"><meta property="og:title" content="{{ $title }} | PakFlex Packaging"><meta property="og:description" content="{{ $description }}"><meta property="og:type" content="website"><meta property="og:url" content="{{ url()->current() }}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/light.css"><script src="/site.js" defer></script>
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Organization', 'name' => $company['name'], 'url' => url('/'), 'logo' => url('/images/pakflex-logo-white.png'), 'address' => ['@type' => 'PostalAddress', 'addressLocality' => 'Faisalabad', 'addressCountry' => 'PK']], JSON_UNESCAPED_SLASHES | JSON_HEX_TAG) !!}</script>
@if($page !== 'home')<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>url('/')],['@type'=>'ListItem','position'=>2,'name'=>$title,'item'=>url()->current()]]], JSON_HEX_TAG | JSON_UNESCAPED_SLASHES) !!}</script>@endif
</head>
<body><a class="skip" href="#main">Skip to content</a>
<div class="topbar"><div class="container"><span><i></i> Packaging solutions for manufacturers & exporters</span><span>Faisalabad, Pakistan <b> / </b> Local expertise. Broader possibilities.</span></div></div>
<header><div class="container nav-wrap"><a class="brand" href="/" aria-label="PakFlex Packaging home"><img src="/images/pakflex-logo-white.png" alt="PakFlex Packaging" width="178" height="65"></a><nav id="navigation" aria-label="Main navigation">@foreach(['/' => 'Home', '/about' => 'About Us', '/products' => 'Products', '/industries' => 'Industries', '/custom-packaging' => 'Custom Packaging', '/quality' => 'Quality', '/contact' => 'Contact'] as $href => $label)<a href="{{ $href }}" @if(request()->getPathInfo() === $href) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav><a class="button nav-quote" href="/request-a-quote">Request a Quote <span>↗</span></a><button class="menu-toggle" aria-label="Open menu" aria-controls="navigation" aria-expanded="false">☰</button></div></header>
<main id="main">
@if($page === 'home')
<section class="hero"><div class="container hero-inner"><div class="hero-copy"><p class="eyebrow"><span></span> BUILT AROUND YOUR PRODUCT</p><h1>Flexible Packaging.<br><em>Reliable Protection.</em></h1><p class="hero-description">Customized polybags, PVC films and packaging solutions for textile, garment, industrial and consumer-product manufacturers.</p><div class="button-row"><a class="button green" href="/request-a-quote">Request a Quote <span>↗</span></a><a class="button outline" href="https://wa.me/{{ preg_replace('/\\D/', '', $company['whatsapp']) }}?text={{ rawurlencode('Hello PakFlex Packaging, I would like to discuss a packaging requirement.') }}">WhatsApp us <span>↗</span></a></div><a class="hero-phone" href="tel:{{ preg_replace('/[^+\\d]/', '', $company['whatsapp']) }}">Talk to Faheem Bilal <strong>{{ $company['phone_display'] }}</strong></a><div class="hero-specs">Custom sizes <b>·</b> Materials <b>·</b> Thickness <b>·</b> Printing <b>·</b> Packing</div></div><div class="hero-media">@include('partials.hero-media')<div class="hero-product-photos"><a href="/products/polybags"><img src="/images/garment-packaging.png" alt="Folded garments in transparent polybags" width="1280" height="1280"><span>Polybags <b>↗</b></span></a><a href="/products/garment-packaging"><img src="/images/printed-packaging.png" alt="Finished garments in printed packaging bags" width="1280" height="1280"><span>Clear packaging bags <b>↗</b></span></a></div></div></div></section>
<div class="category-strip"><div class="container">@foreach($company['products'] as $key => $item)<a href="/products/{{ $key }}">{{ str_replace([' & Textile Packaging', ' & Packaging', 'Custom Printed Packaging'], ['', '', 'Printed Packaging'], $item['name']) }} <span>↗</span></a>@endforeach</div></div>
<section class="section container about-intro"><div><p class="eyebrow">01 / MEET PAKFLEX</p><h2>Good packaging starts<br>with understanding<br><span class="muted">what’s inside.</span></h2></div><div class="intro-copy"><p class="large-copy">Packaging solutions built around your requirements.</p><p>PakFlex Packaging provides customized plastic films, polybags and flexible packaging solutions for manufacturers, exporters and businesses across multiple industries.</p><p>From material and dimensions to printing and closure, we focus on the details that matter to your product.</p><a class="text-link" href="/about">Get to know PakFlex <span>↗</span></a></div></section>
<section class="section pale"><div class="container"><div class="section-heading"><div><p class="eyebrow">02 / OUR PACKAGING RANGE</p><h2>The right packaging.<br>For every requirement.</h2></div><a class="text-link" href="/products">View all products <span>↗</span></a></div>@include('partials.products', ['selection' => array_intersect_key($company['products'], array_flip(['polybags', 'garment-packaging', 'pp-bags', 'pp-pl-films']))])</div></section>
<section class="textile-feature"><div class="textile-photo"><img src="/images/garment-packaging.png" alt="Finished shirts and socks inside clear protective polybags" loading="lazy"><small>Illustrative finished-product packaging</small></div><div class="textile-copy"><p class="eyebrow light">FROM FABRIC TO FINISHED PRODUCT</p><h2>A better finish.<br>A protected journey.</h2><p>Packaging for garments, hosiery, socks, knitwear and home textiles. Designed around presentation, handling and your buyer’s specifications.</p><div class="tags"><span>Garments</span><span>Hosiery & socks</span><span>Home textiles</span><span>Export requirements</span></div><a class="button green" href="/products/garment-packaging">Explore textile packaging <span>↗</span></a></div></section>
<section class="section container"><div class="section-heading"><div><p class="eyebrow">03 / CUSTOM PACKAGING, CLEAR PROCESS</p><h2>Your requirement.<br>Our starting point.</h2></div><p>Customized packaging solutions according to your product, size, material, thickness, printing and quantity requirements.</p></div>@include('partials.process')<a class="text-link" href="/custom-packaging">Start your packaging journey <span>↗</span></a></section>
@endif

@if($page !== 'home')<section class="page-heading"><div class="container"><div class="breadcrumbs"><a href="/">Home</a><span>/</span>@if($product)<a href="/products">Products</a><span>/</span>@elseif($industry)<a href="/industries">Industries</a><span>/</span>@endif<span>{{ $product['name'] ?? $industry['name'] ?? ucwords(str_replace('-', ' ', $page)) }}</span></div><p class="eyebrow">PAKFLEX PACKAGING / {{ $product ? 'PRODUCT SOLUTIONS' : 'FLEXIBLE SOLUTIONS' }}</p><h1>{{ $title }}</h1><p>{{ $description }}</p></div></section>@endif

@if($page === 'products')<section class="section container"><div class="catalogue-toolbar"><p>Explore our packaging solutions</p><label class="search-label">Search products<input id="product-search" type="search" placeholder="Search bags, films, liners…"></label></div>@include('partials.products', ['selection' => $company['products']])<p id="no-products" hidden>No matching products. <a href="/request-a-quote">Tell us what you need.</a></p></section>@endif

@if($product)<section class="section container product-detail"><div>@include('partials.product-art', ['item' => $product])<p class="caption">Product reference only. Final appearance depends on your agreed specification.</p></div><div><p class="eyebrow">{{ $product['label'] }}</p><h2>Specified for your application.</h2><p>{{ $product['description'] }}</p><h3>Options to discuss</h3><ul class="check-list">@foreach($product['items'] as $option)<li>{{ $option }}</li>@endforeach</ul><a class="button green" href="/request-a-quote?product={{ $slug }}">Request a Quote <span>↗</span></a></div></section><section class="section pale"><div class="container specification"><div><p class="eyebrow">THE DETAILS THAT MATTER</p><h2>Your product.<br>Your specification.</h2><p>Availability, minimum quantity, pricing and lead time are confirmed after reviewing your requirement.</p></div><dl>@foreach(['Material', 'Size', 'Thickness', 'Printing', 'Closure', 'Packing', 'Quantity', 'Application'] as $spec)<div><dt>{{ $spec }}</dt><dd>Available according to requirement</dd></div>@endforeach</dl></div></section>@endif

@if(in_array($page, ['home', 'industries', 'industry']))<section class="section {{ $page === 'home' ? 'pale' : '' }}"><div class="container"><div class="section-heading"><div><p class="eyebrow">{{ $page === 'home' ? '04 / ' : '' }}INDUSTRIES WE SERVE</p><h2>{{ $industry ? 'Packaging that fits your sector.' : 'Different industries. One focus.' }}</h2></div><p>From individual presentation to bulk protection, start with your product and the way it moves.</p></div>@if($industry)@include('partials.products', ['selection' => array_intersect_key($company['products'], array_flip($industry['products']))])<div class="notice"><h3>Buying for export?</h3><p>Share your destination, buyer’s packing instructions, labeling, carton quantities and documentation requirements. Delivery arrangements and suitability are confirmed for each order.</p></div>@else<div class="industry-grid">@foreach($company['industries'] as $key => $entry)<a href="/industries/{{ $key }}" class="industry-card"><span class="industry-number">0{{ $loop->iteration }} <b>↗</b></span><h3>{{ $entry['name'] }}</h3><p>{{ $entry['description'] }}</p><span class="text-link">Explore solutions →</span></a>@endforeach</div>@endif</div></section>@endif

@if(in_array($page, ['home', 'about']))<section class="section container"><div class="section-heading"><div><p class="eyebrow">WHY PAKFLEX</p><h2>Practical thinking.<br>Dependable communication.</h2></div><p>Our approach is simple: understand the requirement, agree the specification, and keep the conversation clear.</p></div><div class="benefit-grid">@foreach(['Custom specifications' => 'Packaging according to your product, dimensions and packing requirements.', 'Multiple material options' => 'PE, PVC and other packaging materials according to application.', 'Custom printing' => 'Artwork and branding developed around your product presentation.', 'A B2B focus' => 'Solutions for manufacturers, textile exporters and bulk buyers.', 'Direct communication' => 'Discuss your requirement directly with our sales team.', 'Quotation support' => 'Clear specifications and commercial terms before production.'] as $heading => $copy)<div><span class="benefit-icon">{{ ['⌁', '▱', '✳', '▦', '↗', '≡'][$loop->index] }}</span><h3>{{ $heading }}</h3><p>{{ $copy }}</p></div>@endforeach</div></section>@endif

@if($page === 'about')<section class="section pale"><div class="container specification"><div><p class="eyebrow">BASED IN FAISALABAD, PAKISTAN</p><h2>Close to the needs<br>of textile businesses.</h2></div><div><p class="large-copy">PakFlex Packaging supplies flexible packaging solutions for manufacturers, exporters and businesses.</p><p>We focus on understanding each customer’s requirements and supplying packaging according to the agreed material, dimensions, thickness, printing, closure and quantity.</p><a class="button green" href="/contact">Talk to our sales team ↗</a>@if($company['profile'])<a class="text-link" href="{{ $company['profile'] }}">Download company profile ↓</a>@else<p>Company profile information is available through our sales team.</p>@endif</div></div></section>@endif

@if($page === 'custom-packaging')<section class="section container"><div class="section-heading"><h2>From a clear brief<br>to the right pack.</h2><p>We can develop packaging according to your required dimensions, material, thickness, printing, closure and packing specifications.</p></div>@include('partials.process')<div class="notice"><h3>Prepare your packaging brief</h3><p>Include product dimensions, a reference sample or photograph, your preferred material, quantity, artwork and delivery destination. If you are unsure about a specification, tell us how the packaging will be used.</p></div><a class="button green" href="/request-a-quote">Start your packaging inquiry ↗</a></section>@endif

@if(in_array($page, ['home', 'quality']))<section class="section quality-section"><div class="container specification"><div><p class="eyebrow light">QUALITY IN THE DETAILS</p><h2>Consistency starts<br>with a clear specification.</h2><p>We focus on maintaining consistency in the agreed packaging specifications, including material, dimensions, thickness, printing and packing.</p><a class="text-link" href="{{ $page === 'quality' ? '/request-a-quote' : '/quality' }}">{{ $page === 'quality' ? 'Discuss your specifications' : 'Our approach to quality' }} <span>↗</span></a></div><div class="quality-list">@foreach(['Material specification', 'Dimension checking', 'Thickness verification', 'Printing inspection', 'Sealing quality', 'Packing verification', 'Final product inspection'] as $point)<div><span>✓</span>{{ $point }}</div>@endforeach</div></div></section>@endif

@if(in_array($page, ['home', 'request-a-quote', 'product']))<section class="section container quote-section" id="quote"><div class="quote-intro"><p class="eyebrow">LET’S BUILD YOUR PACKAGING BRIEF</p><h2>Tell us<br>what you need.</h2><p>Share a few details about your product. We’ll have the information needed to discuss a suitable packaging solution.</p><div class="contact-person"><span class="avatar">FB</span><div><strong>{{ $company['contact'] }}</strong><span>{{ $company['role'] }}</span></div></div><p>{{ $company['location'] }}</p><div class="quote-help"><h3>Not sure about the material?</h3><p>Describe your product and application. Leave the specifications you’re unsure about blank.</p></div></div><div>@include('partials.form')</div></section>@endif

@if($page === 'contact')<section class="section container contact-layout"><div><p class="eyebrow">YOUR DIRECT POINT OF CONTACT</p><h2>{{ $company['contact'] }}</h2><p>{{ $company['role'] }}</p><div class="contact-lines"><p><span>LOCATION</span>{{ $company['location'] }}</p><p><span>EMAIL</span>@if($company['email'])<a href="mailto:{{ $company['email'] }}">{{ $company['email'] }}</a>@else Please use our quotation form.@endif</p><p><span>PHONE / WHATSAPP</span>@if($company['whatsapp'])<a href="https://wa.me/{{ preg_replace('/\D/', '', $company['whatsapp']) }}">{{ $company['whatsapp'] }}</a>@else Direct WhatsApp contact will be available here.@endif</p></div><a class="button green" href="/request-a-quote">Send your requirement ↗</a></div><div class="location-card"><div class="map-grid"><div class="location-dot"></div><h3>Faisalabad</h3><span>PUNJAB, PAKISTAN</span></div><p>Our business is based in Faisalabad. Contact sales to arrange a meeting.</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Faisalabad%2C%20Pakistan" target="_blank" rel="noopener">Explore the city on Google Maps ↗</a></div></section>@endif

@if(in_array($page, ['home', 'products', 'custom-packaging']))<section class="section pale"><div class="container faq-layout"><div><p class="eyebrow">BUYER INFORMATION</p><h2>A few things<br>you may want to know.</h2><a class="text-link" href="/contact">Have another question? ↗</a></div><div>@foreach($company['faqs'] as $question => $answer)<details><summary>{{ $question }}<span>+</span></summary><p>{{ $answer }}</p></details>@endforeach</div></div></section>@endif

@if($page === 'privacy')<section class="section container prose"><h2>How your enquiry is handled</h2><p>We collect the contact details, business requirements and optional files you submit to prepare and respond to your packaging enquiry. Fields marked as required allow us to identify your business and contact you.</p><p>Enquiry records and files are stored privately on the website’s server. They are not published on the website. Please avoid including sensitive personal information in your artwork or specification.</p><p>You can request a correction or deletion by contacting the sales team, quoting your enquiry reference. Information is retained while needed for your enquiry and related business records.</p><p>The website uses essential session cookies for form security and submission feedback. No advertising or analytics tools are currently integrated. External links, including WhatsApp and Google Maps, follow their respective providers’ privacy practices.</p></section>@endif
@if($page === 'image-credits')<section class="section container prose"><h2>Photography & illustrations</h2><p>Images show packaging materials and industry context. They do not depict PakFlex facilities or confirm a particular supplied product.</p><p>The bedding, garment, printed-bag and film images are AI-generated product mockups created for this website. They illustrate packaging formats and are not photographs of confirmed PakFlex products.</p><p>Stock images are used under the <a href="https://www.pexels.com/license/">Pexels License</a>. Product format illustrations are created for this website. The PakFlex logo was supplied by the company; a white-background version was prepared for the website.</p><p>The PP, PL, PEVA, EVA and non-woven bag images are product format illustrations created for this website. The flyer bag photograph is “<a href="https://www.flickr.com/photos/185086713@N05/48934840778">Things You Need To Consider For Picking the Right Mailer Size</a>” by <a href="https://www.flickr.com/photos/185086713@N05">stevieoakley</a>, used under <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>.</p></section>@endif

<section class="final-cta"><div class="container"><div><p class="eyebrow">YOUR NEXT PACKAGING SOLUTION STARTS HERE</p><h2>Let’s get your requirements right.</h2></div><a class="button" href="/request-a-quote">Request a Quote <span>↗</span></a></div></section>
</main>
<footer><div class="container footer-grid"><div><a class="footer-brand" href="/">PAK<span>FLEX</span><small>PACKAGING</small></a><p>Flexible Packaging.<br>Reliable Protection.</p><p class="footer-small">Customized packaging for manufacturers, exporters and businesses.</p></div><div><h3>COMPANY</h3>@foreach(['about'=>'About Us','industries'=>'Industries','custom-packaging'=>'Custom Packaging','quality'=>'Quality','contact'=>'Contact'] as $key=>$label)<a href="/{{ $key }}">{{ $label }}</a>@endforeach</div><div><h3>OUR PRODUCTS</h3>@foreach($company['products'] as $key=>$item)<a href="/products/{{ $key }}">{{ $item['name'] }}</a>@endforeach</div><div><h3>LET’S TALK PACKAGING</h3><strong>{{ $company['contact'] }}</strong><p>{{ $company['role'] }}<br>{{ $company['location'] }}</p>@if($company['email'])<a href="mailto:{{ $company['email'] }}">{{ $company['email'] }}</a>@endif<a class="footer-cta" href="/request-a-quote">Send your requirement ↗</a>@if($company['whatsapp'])<a href="tel:{{ preg_replace('/[^+\\d]/', '', $company['whatsapp']) }}">{{ $company['phone_display'] }}</a><a href="https://wa.me/{{ preg_replace('/\\D/', '', $company['whatsapp']) }}">WhatsApp ↗</a>@endif</div></div><div class="container footer-bottom"><span>© {{ date('Y') }} PakFlex Packaging. All rights reserved.</span><div><a href="/privacy">Privacy</a><a href="/image-credits">Image credits</a><a href="#main">Back to top ↑</a></div></div></footer>
@if($company['whatsapp'])<a class="floating-contact" aria-label="Discuss your packaging on WhatsApp" href="https://wa.me/{{ preg_replace('/\D/', '', $company['whatsapp']) }}?text={{ rawurlencode('Hello PakFlex Packaging, I would like to discuss a packaging requirement.') }}">◉ <span>WhatsApp</span></a>@else<a class="floating-contact" href="/request-a-quote">↗ <span>Talk to sales</span></a>@endif
</body></html>



