<?php

return [
    'name' => 'PakFlex Packaging',
    'tagline' => 'Flexible Packaging. Reliable Protection.',
    'contact' => 'Faheem Bilal',
    'role' => 'Sales & Business Development',
    'location' => 'Faisalabad, Pakistan',
    'email' => env('PAKFLEX_EMAIL'),
    'enquiry_email' => env('PAKFLEX_ENQUIRY_EMAIL'),
    'whatsapp' => env('PAKFLEX_WHATSAPP') ?: '+92 304 0891842',
    'phone_display' => '0304 0891842',
    'hero_image' => '/images/bedding-packaging.png',
    'profile' => env('PAKFLEX_PROFILE'),
    'products' => [
        'polybags' => ['name' => 'Polybags', 'type' => 'bags', 'label' => 'Everyday protection', 'description' => 'Customized polybags for individual products, bulk packing and protective liners, specified around your application.', 'items' => ['Plain Polybags', 'Printed Polybags', 'Hosiery & Socks Bags', 'T-Shirt & Shirt Bags', 'Trouser Bags', 'Hanger Bags', 'Self-Adhesive Bags', 'Zipper Bags', 'Master Bags', 'Liner Bags', 'Custom Polybags']],
        'garment-packaging' => ['name' => 'Garment & Textile Packaging', 'type' => 'garment', 'label' => 'Made for textiles', 'description' => 'Presentation and protection for garments, knitwear, hosiery, socks, towels and home textiles, from individual packs to master bags.', 'items' => ['Garment Bags', 'Shirt & Trouser Bags', 'T-Shirt Bags', 'Socks Packaging', 'Hosiery Packaging', 'Knitwear Packaging', 'Home Textile Packaging', 'Towel Packaging', 'Export Packaging', 'Individual Product Bags', 'Master Packaging Bags']],
        'pvc-packaging' => ['name' => 'PVC Packaging', 'type' => 'roll', 'label' => 'Clarity & versatility', 'description' => 'PVC film and packaging options to discuss according to your application, dimensions, thickness and product requirements.', 'items' => ['PVC Flexible Film', 'PVC Rigid Film', 'PVC Sleeves', 'Transparent PVC Packaging', 'PVC Blister Packaging', 'PVC Clamshell Packaging', 'PVC Protective Film', 'PVC Thermoformed Packaging']],
        'pp-pl-films' => ['name' => 'PP & PL Films', 'type' => 'roll', 'label' => 'Flexible by design', 'description' => 'PP and PL films in rolls and sheets for bag making, wrapping and product packing, supplied to your width, thickness and finish.', 'items' => ['PP Film', 'PL Film', 'Film Rolls', 'Film Sheets', 'Clear & Coloured Film', 'Printed Film', 'Custom Width & Thickness']],
        'bopp-packaging' => ['name' => 'BOPP Packaging', 'type' => 'bags', 'label' => 'Present your product', 'description' => 'BOPP packaging options for textile and retail presentation, with printing and finishing agreed to your requirements.', 'items' => ['BOPP Bags', 'Printed BOPP Packaging', 'Laminated BOPP Packaging', 'Textile Packaging', 'Retail Packaging']],
        'pp-bags' => ['name' => 'PP Bags', 'type' => 'bags', 'label' => 'Crystal-clear finish', 'description' => 'Crisp, high-gloss polypropylene (PP) bags that show garments, hosiery and retail products clearly, with self-adhesive and header options.', 'items' => ['Crystal Clear PP Bags', 'Self-Adhesive (Lip & Tape) PP Bags', 'PP Header Bags', 'PP Shirt & Garment Bags', 'PP Hosiery & Socks Bags', 'Gusseted PP Bags', 'Printed PP Bags']],
        'pl-bags' => ['name' => 'PL Bags', 'type' => 'bags', 'label' => 'Simple & dependable', 'description' => 'Plain and printed PL bags for garments, textiles and everyday product packing, made to your size, thickness and quantity.', 'items' => ['Plain PL Bags', 'Printed PL Bags', 'Self-Adhesive PL Bags', 'Garment PL Bags', 'Bulk Packing PL Bags', 'Custom Size PL Bags']],
        'peva-bags' => ['name' => 'PEVA (PPE) Bags', 'type' => 'bags', 'label' => 'Soft & chlorine-free', 'description' => 'Soft, frosted PEVA bags, a chlorine-free alternative to PVC, for bedding, comforters, blankets and home textile sets.', 'items' => ['PEVA Zipper Bags', 'Bedding & Comforter Bags', 'Blanket & Quilt Bags', 'Bags with Carry Handles', 'Piped-Edge PEVA Bags', 'Frosted & Clear PEVA', 'PEVA Film']],
        'flyer-bags' => ['name' => 'Flyer Bags', 'type' => 'bags', 'label' => 'Ready to ship', 'description' => 'Tamper-evident courier and mailer flyer bags for e-commerce and dispatch, with permanent self-seal strips and optional printing.', 'items' => ['Courier Flyer Bags', 'E-commerce Mailer Bags', 'Tamper-Evident Seal Bags', 'Bags with POD Pocket', 'White, Grey & Black Flyers', 'Printed Flyer Bags', 'Custom Sizes']],
        'eva-bags' => ['name' => 'EVA Bags (China)', 'type' => 'bags', 'label' => 'Imported frosted finish', 'description' => 'Frosted matte EVA bags with slider zippers, sourced from China, for garments, accessories and premium retail presentation.', 'items' => ['EVA Slider Zipper Bags', 'Frosted Matte EVA Bags', 'Garment & T-Shirt EVA Bags', 'Accessory & Cosmetic Pouches', 'Printed EVA Bags', 'EVA Film']],
        'nonwoven-bags' => ['name' => 'Non-Woven Bags', 'type' => 'bags', 'label' => 'Reusable & strong', 'description' => 'Reusable non-woven PP fabric bags for retail, promotions and textile packing, printed with your logo in the GSM and size you need.', 'items' => ['Loop Handle Bags', 'D-Cut Bags', 'W-Cut (Vest) Bags', 'Box Bags with Gusset', 'Zipper Non-Woven Bags', 'Bedding & Garment Covers', 'Logo Printed Non-Woven Bags']],
        'custom-printed-packaging' => ['name' => 'Custom Printed Packaging', 'type' => 'printed', 'label' => 'Your brand, clearly', 'description' => 'Turn your artwork into customized packaging designed around your brand and product requirements.', 'items' => ['Logo Printed Bags', 'Custom Artwork', 'Product Information Printing', 'Barcode Printing', 'Multi-Color Printing', 'Branded Packaging']],
    ],
    'industries' => [
        'textile-garments' => ['name' => 'Textile & Apparel', 'description' => 'Packaging for garment manufacturers, knitwear, hosiery, socks, textile exporters and apparel brands.', 'products' => ['garment-packaging', 'polybags', 'pp-bags', 'eva-bags', 'custom-printed-packaging']],
        'home-textile' => ['name' => 'Home Textiles', 'description' => 'Packaging requirements for towels, bed linen, made-ups and other home textile products.', 'products' => ['garment-packaging', 'peva-bags', 'pvc-packaging', 'nonwoven-bags', 'polybags']],
        'industrial' => ['name' => 'Industrial & Logistics', 'description' => 'Protection for components, manufactured products, warehouse handling and bulk distribution.', 'products' => ['pp-pl-films', 'polybags', 'flyer-bags']],
        'retail' => ['name' => 'Retail & Consumer Products', 'description' => 'Packaging for branded products, retail presentation, e-commerce dispatch and consumer goods, specified to suit the product.', 'products' => ['bopp-packaging', 'flyer-bags', 'nonwoven-bags', 'pl-bags', 'custom-printed-packaging']],
    ],
    'faqs' => [
        'What packaging products do you supply?' => 'We supply customized polybags, PP and PL bags, PEVA and EVA bags, flyer bags, non-woven bags, garment packaging, PVC packaging, PP and PL films, BOPP packaging and printed flexible packaging according to customer requirements.',
        'Can packaging be customized?' => 'Yes. Share your size, material, thickness, printing, closure, quantity and application. We will discuss the appropriate specification with you.',
        'Do you provide printed polybags?' => 'Yes. Custom printed packaging can be supplied according to agreed artwork and specifications.',
        'Can you supply garment packaging?' => 'Yes. Garment, hosiery, socks, knitwear and home textile packaging can be developed according to product requirements.',
        'How can I request a quotation?' => 'Use the quotation form to send your product, size, material, thickness, printing requirement and quantity. You can also attach artwork or a specification.',
        'Do you supply internationally?' => 'Contact our sales team to discuss your location, product requirements and delivery arrangements. Availability, documentation and commercial terms are confirmed for each enquiry.',
    ],
];
